#!/usr/bin/env python

from docopt import docopt

from ifixittozim import logger, VERSION
from ifixittozim.get_categories import get_categories
from ifixittozim.get_guides import get_guides
from ifixittozim.get_images import get_images
from ifixittozim.generate_website import generate_website

help = (
    """Usage: ifixit2zim [--get-categories] [--get-guides] [--get-images] """
    """[--generate-website] [-u IFIXIT_API_BASE_URL] """
    """

-h --help                       Display this help message

--get-categories                Download categories
--get-guides                    Download guides
--get-images                    Download images
--generate-website              Generate static website files from items downloaded
-u --ifixit-api-base-url=<url>  iFixit API Base URL (default to https://www.ifixit.com/api/2.0)

This script is used to produce a ZIM file (and any intermediate state) """
"""of iFixit resources (step by step guides, ...)."""
)

def main(arguments):
    
    # actions constants
    DO_GET_CATEGORIES = arguments.get("--get-categories", False)
    DO_GET_GUIDES = arguments.get("--get-guides", False)
    DO_GET_IMAGES = arguments.get("--get-images", False)
    DO_GENERATE_WEBSITE = arguments.get("--generate-website", False)

    IFIXIT_API_BASE_URL = (
        arguments.get("--ifixit-api-base-url")
        or "https://www.ifixit.com/api/2.0"
    )

    if DO_GET_CATEGORIES:
        logger.info("Getting categories from {}".format(IFIXIT_API_BASE_URL))
        get_categories(ifixit_api_base_url=IFIXIT_API_BASE_URL)

    if DO_GET_GUIDES:
        logger.info("Getting guides from {}".format(IFIXIT_API_BASE_URL))
        get_guides(ifixit_api_base_url=IFIXIT_API_BASE_URL)

    if DO_GET_IMAGES:
        logger.info("Getting images from {}".format(IFIXIT_API_BASE_URL))
        get_images(ifixit_api_base_url=IFIXIT_API_BASE_URL)

    if DO_GENERATE_WEBSITE:
        logger.info("Generating website")
        generate_website()


if __name__ == "__main__":
    main(docopt(help, version=VERSION))