name: QA

on: [push, pull_request]

env:
  # black default
  MAX_LINE_LENGTH: 88

jobs:
  check-qa:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Check black formatting
        run: |
          pip install black==22.3.0
          black --version
          black --check .

      - name: Check flake8 linting
        run: |
          pip install flake8==3.9.2
          flake8 --version
          flake8 . --count --max-line-length=$MAX_LINE_LENGTH --statistics

      - name: Check import order with isort
        run: |
          pip install isort==5.9.3
          isort --version
          isort --profile black --check .
