name: release
on:
  release:
    types: [published]
    tags:
      - v*

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Build sdist and wheel
        run: |
          pip install --upgrade setuptools pip wheel
          python3 setup.py sdist
          python3 setup.py bdist_wheel

      - name: Push release to PyPI
        if: github.event_name == 'release'
        run: |
          pip install --upgrade twine
          twine check dist/*
          twine upload dist/*
